name: main

 on: push

 jobs:
   test:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
           node-version: 16.x
           cache: "npm"
       - name: Install dependencies
         run: npm ci
       - name: Run unit tests
         run: npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI